This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./arbeit.ist..............done (14 attributes redefined, 0 ignored).
Scanning input file arbeit.acr....done (69 entries accepted, 0 rejected).
Sorting entries....done (493 comparisons).
Generating output file arbeit.acn....done (40 lines written, 0 warnings).
Output written in arbeit.acn.
Transcript written in arbeit.alg.
