package com.github.katjahahn.parser.sections.rsrc.version;

public enum DrvFileSubtype {
	
	VFT2_DRV_COMM,
	VFT2_DRV_DISPLAY,
	VFT2_DRV_INSTALLABLE,
	VFT2_DRV_KEYBOARD,
	VFT2_DRV_LANGUAGE,
	VFT2_DRV_MOUSE,
	VFT2_DRV_NETWORK,
	VFT2_DRV_PRINTER,
	VFT2_DRV_SOUND,
	VFT2_DRV_SYSTEM,
	VFT2_DRV_VERSIONED_PRINTER,
	VFT2_DRV_UNKNOWN,
}
