package com.github.katjahahn.msdos;

import com.github.katjahahn.HeaderKey;

public enum MSDOSHeaderKey implements HeaderKey {
	SIGNATURE_WORD, LAST_PAGE_SIZE, FILE_PAGES, RELOCATION_ITEMS, 
	HEADER_PARAGRAPHS, MINALLOC, MAXALLOC, INITIAL_SS, INITIAL_SP, 
	COMPLEMENTED_CHECKSUM, INITIAL_IP, PRE_RELOCATED_INITIAL_CS, 
	RELOCATION_TABLE_OFFSET, OVERLAY_NR;
}
